### ISSUE TITLE
VPN Kullanma Politikası Ekle

### ISSUE THREAD

**Issue by sinansahin** [bidb/resmi#1]

**Comment by simgesen** [comment]
# VPN Kullanım Politikası 

## Amaç

OMÜ VPN hizmeti ile, mensup ve öğrencilerimizin, sahip oldukları kişisel bilgisayarlar ya da mobil cihazlar yardımıyla, yerleşke dışında bulundukları sürelerde de OMÜ yerleşke IP bloğuna  izinli olan ağ servislerine erişme imkanı bulmaları amaçlanmaktadır.
 
## Kapsam

Bu politika, Ondokuz Mayıs Üniversitesi tarafından yönetilen e-posta sistemlerinden faydalanan tüm akademik ve idari personel ile birlikte tüm öğrencileri kapsamaktadır.

## Tanım

VPN, Virtual Private Network'un (Sanal Özel Ağ'ın) kısaltmasıdır. VPN ile Internet erişimli ağlar üzerinden şifreli bir tünel aracılığı ile; iletişimin üçüncü kişiler tarafından dinlenmesi engellenerek
 ve içeriğinin bütünlüğü (haberleşme içeriğinin değiştirilmemesi) sağlanarak; kullanıcıların güvenli 
bir şekilde kendi kurum ve kurum kaynaklarına erişimleri sağlanmaktadır.

## Hizmet Şartları

1. OMÜ/VPN hizmetinden sadece OMÜ mensupları yararlanabilir. OMÜ/VPN hizmetinden yararlanmak için hizmeti alacak kullanıcının OMÜ/VPN kullanım kurallarını okuması ve imzalaması gerekmektedir.

2. OMÜ/VPN hizmetine erişim sadece “Cisco Anyconnect SSL VPN Client” yazılımı ile yapılabilmektedir. Kullanıcı bu yazılımı kurmadan önce bilgisayarında oluşabilecek olası sorunlara karşı gereken yedeklemesini almalıdır. Kurulan bu yazılımdan dolayı oluşabilecek her türlü sorumluluk kullanıcıya aittir. 

3. OMÜ/BİDB, OMÜ/VPN hizmetini “Cisco Anyconnect SSL VPN Client” programının kullanılabildiği cihazlar üzerinden vermektedir. Bu programın kurulumunun gerçekleştirilemediği ve üreticinin desteklemediği bir platform dolayısıyla OMÜ/BİDB sorumlu tutulamaz.

4. OMÜ/VPN hizmeti OMÜ/NET ağına güvenli erişimin sağlanması ve kullanıcıların akademik amaçlı servislerden yararlanması için hizmet vermektedir, bunun dışında kullanılması yasaktır. 

5. OMÜ/VPN üzerinden herhangi bir servis (Proxy, DHCP, BOOTP, DNS vb.) verilemez, herhangi bir yönlendirme protokolü anonsu yapılamaz. 

6. OMÜ/VPN bağlantı hizmeti kişiseldir, başka bir kullanıcıya devredilemez. Hizmet alan kullanıcılar bağlantı yaptıkları cihazdan ve bu cihazla yapılan her türlü kural dışı hareketten sorumludurlar. 

7. OMÜ/VPN altyapısında kullanılan protokol ve servis standartlarında oluşabilecek herhangi bir zaafiyet ve açıklık sebebiyle OMÜ/BİDB soumlu tutulamaz. OMÜ/BİDB bu tür açıkları en kısa sürede gidermek ile yükümlüdür. 

8. Lisanssız yazılım, film ve müzik dosyaları OMÜ/VPN üzeriden herhangi bir yöntemle dağıtılamaz. Bu konu ile ilgili bütün yasal sorumluluk kullanıcıya aittir. 

9. OMÜ/VPN kullanıcısının, OMÜ/NET dahilinde ya da haricindeki bir sisteme, ağ kaynağına veya ağ üzerinden hizmet veren bir servise saldırı amaçlı (port tarama, paket dinleme, büyük band genişliği harcama vb) herhangi bir zarar verecek girişimde bulunması kesinlikle yasaktır. 

10. Kullanıcıların, kendi bilgisayarlarının işletim sistemi yamalarını yapmaları zorunludur. OMÜ/BİDB, bu yamaların kontrolünü yapmak için, uzaktan port tarama programları kullanabilir. Bu yamaların uygulanmaması durumunda kullanıcıdan izin alınmaksızın yamalar uygulanana dek erişim hizmeti kesilebilecektir. 

11. Kullanıcı, bakım çalışması amacı ile planlı olarak ya da sistem aksaklıkları sebebi ile OMÜ/VPN hizmetine erişimde beklenmedik kesintiler yaşayabilir.

12. OMÜ/BİDB, kullanıcının OMÜ/VPN hizmetini kullanması esnasında herhangi bir hız garantisi vermemektedir. 
13. OMÜ/BİDB, OMÜ/VPN erişim hızını kısıtlamamakla birlikte adil kullanım koşulları çerçevesinde hızın kısıtlanması ve kotalanması hakkını elinde tutar.

14. OMÜ/BİDB bu hizmetler ile ilgili herhangi bir güncelleme ya da değişikliği, OMÜ/BİDB web sayfası, OMÜ/BİDB sosyal medya hesapları ve kullanıcıların OMÜ mail adreslerine mail atılması yoluyla duyurabilir. Yapılacak duyuruların kullanıcının eline geçtiği kabul edilecektir. 

15. OMÜ/BİDB yukarıda belirtilen kuralları değiştirme hakkına sahiptir. 

16. OMÜ/BİDB yukarıda belirtilen kurallara uyulmaması durumunda kullanıcının OMÜ/VPN hizmetini uyarı yapmaksızın kesme hakkına sahiptir.

### Referanslar
[İstanbul Teknik Üniversitesi Bilgi İşlem Daire Başkanlığı](http://www.calismagruplari.itu.edu.tr/eskiler/politikalar-eski/vpn-kullanim-politikalari)

[Ortadoğu Teknik Üniversitesi Bilgi İşlem Daire Başkanlığı](https://faq.cc.metu.edu.tr/tr/sss/odtu-vpn-hizmeti-kullanim-politikasi)

**Comment by sinansahin** [comment]
- Cisco Anyconnect SSL VPN Client programı yerine Forticlient yazılımını kullanıyoruz. 
- Şuan öğrencilere vpn hizmeti sunmuyoruz, o yüzden öğrenci tanımlamasını kaldıralım. 
- ` OMÜ mail adreslerine mail atılması yoluyla ` mail yerine elektronik posta adresleri kelimesini kullanalım. Mümkün olduğunda Türkçe olsun tüm kelimeler.

[README](https://github.com/bidb/resmi/blob/master/README.md) dosyasında belirtilen kurallara uyarak bu politikanın dosyasını oluştur.
